server:
  port: 8080
spring:
  application:
    name: activiti-demo
  datasource:
    url: jdbc:mysql://localhost:3306/workflow_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  main:
    allow-bean-definition-overriding: true
  activiti:
    database-schema: ACTIVITI
    database-schema-update: true
    history-level: full
    db-history-used: true
    async-executor-activate: true
    process-definition-location-prefix: classpath*:**/processes/

project:
  manifest:
    file:
      path: classpath:/default-project.json
